const fs = require("fs");
const store = [
"import { reactive } from \"vue\"",
"",
"const TOKEN_KEY = \"toolhub_token\"",
"const USER_KEY = \"toolhub_user\"",
"",
"const storedToken = localStorage.getItem(TOKEN_KEY)",
"const storedUser = localStorage.getItem(USER_KEY)",
"",
"export const auth = reactive({",
"  token: storedToken || null,",
"  user: storedUser ? JSON.parse(storedUser) : null,",
"  get isLoggedIn() { return !!this.token },",
"",
"  login(token, user) {",
"    this.token = token",
"    this.user = user",
"    localStorage.setItem(TOKEN_KEY, token)",
"    localStorage.setItem(USER_KEY, JSON.stringify(user))",
"  },",
"",
"  logout() {",
"    this.token = null",
"    this.user = null",
"    localStorage.removeItem(TOKEN_KEY)",
"    localStorage.removeItem(USER_KEY)",
"  },",
"})",
"",
"export function authHeaders() {",
"  const headers = { \"Content-Type\": \"application/json\" }",
"  if (auth.token) headers[\"Authorization\"] = \"Token \" + auth.token",
"  return headers",
"}",
]
fs.writeFileSync("src/auth.js", store.join("\n"), "utf-8");
console.log("auth.js created");