# Generated by Django 6.0.6 on 2026-07-03 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_seed_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(default=0)),
                ("file_type", models.CharField(blank=True, default="", max_length=100)),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "share_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("downloads_count", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
