# Generated by Django 6.0.6 on 2026-07-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_uploadedfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_size",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="original_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
