# Generated by Django 6.0.6 on 2026-07-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_uploadedfile_file_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedpassword",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
