# Generated by Django 6.0.6 on 2026-07-03 19:33

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_generatedpassword_user_iplookuphistory_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generatedpassword",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "生成的密码",
                "verbose_name_plural": "密码管理",
            },
        ),
        migrations.AlterModelOptions(
            name="iplookuphistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "IP查询记录",
                "verbose_name_plural": "IP查询记录管理",
            },
        ),
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "笔记",
                "verbose_name_plural": "笔记管理",
            },
        ),
        migrations.AlterModelOptions(
            name="savedqrcode",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "保存的二维码",
                "verbose_name_plural": "二维码管理",
            },
        ),
        migrations.AlterModelOptions(
            name="todo",
            options={
                "ordering": ["completed", "-created_at"],
                "verbose_name": "待办事项",
                "verbose_name_plural": "待办事项管理",
            },
        ),
        migrations.AlterModelOptions(
            name="toolusage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "工具使用记录",
                "verbose_name_plural": "使用统计",
            },
        ),
        migrations.AlterModelOptions(
            name="uploadedfile",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "上传的文件",
                "verbose_name_plural": "文件管理",
            },
        ),
        migrations.AlterField(
            model_name="generatedpassword",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="generatedpassword",
            name="has_digits",
            field=models.BooleanField(default=True, verbose_name="包含数字"),
        ),
        migrations.AlterField(
            model_name="generatedpassword",
            name="has_lower",
            field=models.BooleanField(default=True, verbose_name="包含小写字母"),
        ),
        migrations.AlterField(
            model_name="generatedpassword",
            name="has_symbols",
            field=models.BooleanField(default=True, verbose_name="包含特殊字符"),
        ),
        migrations.AlterField(
            model_name="generatedpassword",
            name="has_upper",
            field=models.BooleanField(default=True, verbose_name="包含大写字母"),
        ),
        migrations.AlterField(
            model_name="generatedpassword",
            name="length",
            field=models.IntegerField(verbose_name="密码长度"),
        ),
        migrations.AlterField(
            model_name="generatedpassword",
            name="note",
            field=models.TextField(blank=True, default="", verbose_name="备注说明"),
        ),
        migrations.AlterField(
            model_name="generatedpassword",
            name="password",
            field=models.CharField(max_length=128, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="generatedpassword",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="iplookuphistory",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="城市"),
        ),
        migrations.AlterField(
            model_name="iplookuphistory",
            name="country",
            field=models.CharField(blank=True, max_length=100, verbose_name="国家"),
        ),
        migrations.AlterField(
            model_name="iplookuphistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="查询时间"),
        ),
        migrations.AlterField(
            model_name="iplookuphistory",
            name="ip",
            field=models.CharField(blank=True, max_length=50, verbose_name="IP地址"),
        ),
        migrations.AlterField(
            model_name="iplookuphistory",
            name="org",
            field=models.CharField(blank=True, max_length=200, verbose_name="运营商"),
        ),
        migrations.AlterField(
            model_name="iplookuphistory",
            name="query",
            field=models.CharField(max_length=200, verbose_name="查询内容"),
        ),
        migrations.AlterField(
            model_name="iplookuphistory",
            name="region",
            field=models.CharField(blank=True, max_length=100, verbose_name="省份"),
        ),
        migrations.AlterField(
            model_name="iplookuphistory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(blank=True, default="", verbose_name="内容"),
        ),
        migrations.AlterField(
            model_name="note",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="标题"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="note",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="savedqrcode",
            name="content",
            field=models.TextField(verbose_name="二维码内容"),
        ),
        migrations.AlterField(
            model_name="savedqrcode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="savedqrcode",
            name="size",
            field=models.IntegerField(default=200, verbose_name="尺寸"),
        ),
        migrations.AlterField(
            model_name="savedqrcode",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="已完成"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=200, verbose_name="任务内容"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="toolusage",
            name="action",
            field=models.CharField(default="use", max_length=50, verbose_name="操作"),
        ),
        migrations.AlterField(
            model_name="toolusage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="使用时间"),
        ),
        migrations.AlterField(
            model_name="toolusage",
            name="detail",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="详情"
            ),
        ),
        migrations.AlterField(
            model_name="toolusage",
            name="tool",
            field=models.CharField(
                choices=[
                    ("notes", "在线笔记"),
                    ("todo", "待办事项"),
                    ("password", "密码生成器"),
                    ("qrcode", "二维码"),
                    ("ip", "IP查询"),
                    ("file", "文件管理"),
                ],
                max_length=20,
                verbose_name="工具",
            ),
        ),
        migrations.AlterField(
            model_name="toolusage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="downloads_count",
            field=models.IntegerField(default=0, verbose_name="下载次数"),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(
                upload_to=core.models.file_upload_path, verbose_name="文件"
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_size",
            field=models.BigIntegerField(
                default=0, editable=False, verbose_name="文件大小"
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_type",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="文件类型"
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="是否收藏"),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="original_filename",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="原始文件名"
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="share_token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="分享令牌"
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
