# Generated by Django 6.0.6 on 2026-07-04 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_generatedpassword_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="upload_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="上传IP"
            ),
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("visit", "页面访问"),
                            ("login", "用户登录"),
                            ("upload", "文件上传"),
                            ("api", "API调用"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="日志类型",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="访问路径"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="请求方法"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="用户代理"),
                ),
                (
                    "detail",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "访问日志",
                "verbose_name_plural": "访问日志",
                "ordering": ["-created_at"],
            },
        ),
    ]
