# Generated by Django 6.0.6 on 2026-07-04 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_uploadedfile_upload_ip_accesslog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conv_type",
                    models.CharField(
                        choices=[
                            ("pdf2word", "PDF转Word"),
                            ("pdf2txt", "PDF提取文本"),
                            ("pdf2images", "PDF转图片"),
                            ("merge_pdf", "合并PDF"),
                            ("split_pdf", "拆分PDF"),
                            ("word2pdf", "Word转PDF"),
                            ("excel2csv", "Excel转CSV"),
                            ("excel2json", "Excel转JSON"),
                        ],
                        max_length=20,
                        verbose_name="转换类型",
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        upload_to="conversions/input/", verbose_name="源文件"
                    ),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="conversions/output/",
                        verbose_name="结果文件",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="原始文件名",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_msg",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件转换记录",
                "verbose_name_plural": "文件转换记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
