# Generated by Django 6.0.6 on 2026-07-16 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_fileconversion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="share_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="分享过期时间"
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="share_max_downloads",
            field=models.PositiveIntegerField(default=0, verbose_name="最大下载次数"),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="share_password",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="分享密码"
            ),
        ),
        migrations.AlterField(
            model_name="toolusage",
            name="tool",
            field=models.CharField(
                choices=[
                    ("notes", "在线笔记"),
                    ("todo", "待办事项"),
                    ("password", "密码生成器"),
                    ("qrcode", "二维码"),
                    ("ip", "IP查询"),
                    ("file", "文件管理"),
                    ("clipboard", "剪贴板"),
                    ("bookmark", "书签"),
                    ("reminder", "提醒"),
                    ("shortlink", "短链接"),
                    ("expense", "账本"),
                    ("text", "文本工具"),
                    ("image", "图片工具"),
                ],
                max_length=30,
                verbose_name="工具",
            ),
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="标题")),
                ("url", models.URLField(max_length=500, verbose_name="网址")),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="分类"
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "open_count",
                    models.PositiveIntegerField(default=0, verbose_name="打开次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "书签",
                "verbose_name_plural": "书签管理",
                "ordering": ["category", "title"],
            },
        ),
        migrations.CreateModel(
            name="ClipboardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="标题"
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "tags",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="标签"
                    ),
                ),
                ("pinned", models.BooleanField(default=False, verbose_name="置顶")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "剪贴板条目",
                "verbose_name_plural": "剪贴板",
                "ordering": ["-pinned", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金额"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="日常", max_length=80, verbose_name="分类"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="备注"
                    ),
                ),
                ("spent_at", models.DateField(verbose_name="日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "账本记录",
                "verbose_name_plural": "个人账本",
                "ordering": ["-spent_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImageProcessHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation", models.CharField(max_length=30, verbose_name="操作")),
                (
                    "original_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="原始文件名",
                    ),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="image-tools/",
                        verbose_name="结果文件",
                    ),
                ),
                (
                    "result_text",
                    models.TextField(blank=True, default="", verbose_name="结果文本"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "图片处理记录",
                "verbose_name_plural": "图片工具记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="标题")),
                ("remind_at", models.DateTimeField(verbose_name="提醒时间")),
                (
                    "repeat",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="重复"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="已完成"),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "提醒",
                "verbose_name_plural": "提醒管理",
                "ordering": ["completed", "remind_at"],
            },
        ),
        migrations.CreateModel(
            name="ShortLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="短码")),
                (
                    "target_url",
                    models.URLField(max_length=1000, verbose_name="目标网址"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=160, verbose_name="标题"
                    ),
                ),
                (
                    "visits",
                    models.PositiveIntegerField(default=0, verbose_name="访问次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "短链接",
                "verbose_name_plural": "短链接管理",
                "ordering": ["-created_at"],
            },
        ),
    ]
