# Generated by Django 6.0.6 on 2026-07-18 15:16

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_uploadedfile_share_expires_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=core.models.image_asset_upload_path,
                        verbose_name="图片",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="原始文件名",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=160, verbose_name="标题"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="分类"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="标签"
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="收藏"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小"),
                ),
                ("width", models.PositiveIntegerField(default=0, verbose_name="宽度")),
                ("height", models.PositiveIntegerField(default=0, verbose_name="高度")),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="内容哈希",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "图片素材",
                "verbose_name_plural": "图片整理",
                "ordering": ["-updated_at"],
            },
        ),
    ]
