# Generated by Django 6.0.6 on 2026-07-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_imageasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageasset",
            name="is_user_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="用户已删除"
            ),
        ),
        migrations.AddField(
            model_name="imageasset",
            name="user_deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="用户删除时间"
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="is_user_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="用户已删除"
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="user_deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="用户删除时间"
            ),
        ),
    ]
