"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Environment variables (production overrides)
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-x(ij1q-^l3f=+p=^8ljb3m+t7d3!n8w9^ok2lofo2^$-dd^p=+")

DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

CSRF_TRUSTED_ORIGINS = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "http://127.0.0.1:8000,http://localhost:8000").split(",")

CORS_ALLOWED_ORIGINS = os.getenv("DJANGO_CORS_ORIGINS", "http://127.0.0.1:8000,http://localhost:8000").split(",")
CORS_ALLOW_ALL_ORIGINS = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY is now loaded from environment

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG is now loaded from environment

# ALLOWED_HOSTS is now loaded from environment


# Application definition

INSTALLED_APPS = [
    "simpleui",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [BASE_DIR / "static",]
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.TokenAuthentication'],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
}


# ===== SimpleUI 后台美化配置 =====
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_DEFAULT_THEME = "admin.lte.css"
SIMPLEUI_LOGO = "/static/images/logo-h.svg"
SIMPLEUI_ICON = {
    "笔记管理": "fas fa-sticky-note",
    "待办事项管理": "fas fa-tasks",
    "密码管理": "fas fa-lock",
    "二维码管理": "fas fa-qrcode",
    "IP查询记录管理": "fas fa-globe",
    "使用统计": "fas fa-chart-bar",
    "文件管理": "fas fa-folder-open",
    "认证和授权": "fas fa-shield-alt",
    "用户": "fas fa-user",
    "用户组": "fas fa-users",
}
SIMPLEUI_CONFIG = {
    "system_keep": True,
    "dynamic": True,
    "menus": [
        {
            "name": "内容管理",
            "icon": "fas fa-edit",
            "models": [
                {"name": "笔记管理", "icon": "fas fa-sticky-note", "url": "/admin/core/note/"},
                {"name": "待办事项管理", "icon": "fas fa-tasks", "url": "/admin/core/todo/"},
                {"name": "文件管理", "icon": "fas fa-folder-open", "url": "/admin/core/uploadedfile/"},
            ],
        },
        {
            "name": "工具数据",
            "icon": "fas fa-tools",
            "models": [
                {"name": "密码管理", "icon": "fas fa-lock", "url": "/admin/core/generatedpassword/"},
                {"name": "二维码管理", "icon": "fas fa-qrcode", "url": "/admin/core/savedqrcode/"},
                {"name": "IP查询记录管理", "icon": "fas fa-globe", "url": "/admin/core/iplookuphistory/"},
            ],
        },
        {
            "name": "系统管理",
            "icon": "fas fa-cog",
            "models": [
                {"name": "使用统计", "icon": "fas fa-chart-bar", "url": "/admin/core/toolusage/"},
                {"name": "用户管理", "icon": "fas fa-user", "url": "/admin/auth/user/"},
                {"name": "用户组", "icon": "fas fa-users", "url": "/admin/auth/group/"},
            ],
        },
    ],
}
